const products = [
    {
      id: 'corona1',
      name: 'Corona de porcelana',
      category: 'Coronas',
      image: 'https://www.clinicaferrusbratos.com/app/uploads/corona-de-zirconio-ventajas.jpg',
      price: 120,
      brand: 'Marca X',
      rating: 4.5,
      numReviews: 10,
      description: 'Corona de porcelana de alta calidad.',
    },
    {
      id: 'implante1',
      name: 'Implante dental',
      category: 'Implantes',
      image: 'https://www.implanet.cl/wp-content/uploads/2022/06/de-que-esta-hecha-la-corona-de-un-implante.jpg',
      price: 300,
      brand: 'Marca Y',
      rating: 4.7,
      numReviews: 15,
      description: 'Implante dental de titanio.',
    },
    {
      id: 'puente1',
      name: 'Puente dental',
      category: 'Puentes',
      image: 'https://clinicadentalservet.com/wp-content/uploads/2023/03/tipos-puentes-dentales.jpg',
      price: 200,
      brand: 'Marca Z',
      rating: 4.6,
      numReviews: 12,
      description: 'Puente dental de porcelana.',
    },
    {
      id: 'incrustacion1',
      name: 'Incrustación dental',
      category: 'Incrustaciones',
      image: 'https://clinicadentalgaudi.com/wp-content/uploads/2021/03/iStock-1152517544.jpg',
      price: 150,
      brand: 'Marca X',
      rating: 4.5,
      numReviews: 10,
      description: 'Incrustación dental de composite.',
    },
    {
      id: 'corona2',
      name: 'Corona de zirconio',
      category: 'Coronas',
      image: 'https://www.clinicaferrusbratos.com/app/uploads/corona-de-zirconio-ventajas.jpg',
      price: 140,
      brand: 'Marca Y',
      rating: 4.8,
      numReviews: 20,
      description: 'Corona de zirconio de alta resistencia.',
    },
    {
      id: 'implante2',
      name: 'Implante dental de cerámica',
      category: 'Implantes',
      image: 'https://clinicavargasridao.com/wp-content/uploads/2020/02/implantes-zirconio.jpg',
      price: 350,
      brand: 'Marca Z',
      rating: 4.7,
      numReviews: 18,
      description: 'Implante dental de cerámica.',
    },
    {
      id: 'puente2',
      name: 'Puente dental de zirconio',
      category: 'Puentes',
      image: 'https://www.dentaltix.com/es/sites/default/files/puente-dental-protesis-fija.jpg',
      price: 220,
      brand: 'Marca X',
      rating: 4.6,
      numReviews: 14,
      description: 'Puente dental de zirconio.',
    },
    {
      id: 'incrustacion2',
      name: 'Incrustación dental de porcelana',
      category: 'Incrustaciones',
      image: 'https://galvan.es/wp-content/uploads/2021/05/incrustacion-porcelana-onlay.jpg',
      price: 160,
      brand: 'Marca Y',
      rating: 4.5,
      numReviews: 12,
      description: 'Incrustación dental de porcelana.',
    },
    {
      id: 'corona3',
      name: 'Corona de metal',
      category: 'Coronas',
      image: 'https://soluciondental.pe/wp-content/uploads/2019/07/corona-dental-met%C3%A1lica.jpg',
      price: 100,
      brand: 'Marca Z',
      rating: 4.4,
      numReviews: 8,
      description: 'Corona de metal de alta durabilidad.',
    },
    {
      id: 'implante3',
      name: 'Implante dental de zirconio',
      category: 'Implantes',
      image: 'https://clinicamuller.es/wp-content/uploads/2016/06/implante-zirconio.jpg',
      price: 400,
      brand: 'Marca X',
      rating: 4.9,
      numReviews: 22,
      description: 'Implante dental de zirconio.',
    },
  ];